version: '1'

services:
  db:
    build: sql
    environment:
      MYSQL_ROOT_PASSWORD: bigpassword
      MYSQL_DATABASE: questions
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  web:
    build: php
    ports: 
      - "8000:80"